#!/usr/bin/env ruby

def checkRubyVersion
  if (Gem.ruby_version < Gem::Version.create("1.9.3"))
    throw "Unsopported ruby version found, please install and activate at least ruby 1.9.3!"
  end
end

checkRubyVersion

